# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Use dotnet sdk 3.x'
  inputs:
    version: 3.x
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '${{variables.solution}}'
    feedsToUse: 'select'
 
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '${{variables.solution}}'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '${{variables.solution}}'

# Publish Package as Build Artifact
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'DwC-A_Driver'
    pathToPublish: 'DwC-A_Driver\bin\Debug\*.nupkg'

