name: .NET

env:
  buildConfiguration: "Release"
  driverBaseName: "DwC-A_LinQPad_Driver"

on:
  push:
    branches: 
      - '*'
      - '*/*'
  pull_request:
    branches: 
      - '*'
      - '*/*'
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --verbosity normal
    - name: Show workspace
      run: echo $GITHUB_WORKSPACE
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: DwC-A_LINQPad_Driver.nupkg
        path: DwC-A_LINQPad_Driver\DwC-A_Driver\bin\Release\DwC-A_LinQPad_Driver.2.0.5.nupkg
